"""Add cascade delete for cards

Revision ID: 3539dc4708a3
Revises: 00b3a4c715fe
Create Date: 2025-04-19 19:33:40.665897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3539dc4708a3'
down_revision: Union[str, None] = '00b3a4c715fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_section_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_section_id_fkey', 'cards', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
